### ISSUE TITLE
[account-web-vault]: Modal CSS conflicts with bootstrap css

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#237]
### Problem

The connect  modal does not display when the package is used in a js framework set up with bootstrap CSS, this happens as a result of CSS conflict when the `bootstrap/dist/css/bootstrap.min.css` is imported

see the discord thread of the observation :
https://discord.com/channels/664594912460668960/1026461094421729340/1028925314300129330

cc @nick-verida @tahpot

**Comment by cmcWebCode40** [comment]
@tahpot, 

While going through ShinzoHiro#3741 observation  concerning this error from the discord channel 
I could see where bootstrap defined this global CSS rule which overrides the `hidden` attribute set in our account vault modal 

```css

// Hidden attribute
//
// Always hide an element with the `hidden` HTML attribute.

[hidden] {
  display: none !important;
}


```

Removing the `hidden` attribute in the parent modal div from the `account-web-vault` packages resolves this because the parent div with class name `verida-modal-wrapper` has its initial display set to `none` .

What are your thoughts on this?

cc @nick-verida @aurelticot
